# -*- coding: utf-8 -*-
"""DNN _SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kQB9Wq8nvvp2u3fM6mGGiqlG4CmeHoa_
"""

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, classification_report
from sklearn import svm
import numpy as np
import matplotlib.pyplot as plt

data = load_breast_cancer()

X = data.data
Y = data.target

X_train, X_test, Y_train, Y_test = train_test_split(X,  Y, test_size=0.2, random_state=42)

X_train.shape, X_test.shape

X_train.shape
image = X_train.reshape(210,65)
plt.imshow(image)

Y_train.shape
image_1 = Y_train.reshape(65,7)
plt.imshow(image_1)

X_test.shape
image_3 = X_test.reshape(60,57)
plt.imshow(image_3)

Y_test.shape
image_4 = Y_test.reshape(57,2)
plt.imshow(image_4)

classifier= svm.SVC(kernel = 'linear', gamma = 'auto', C = 2)
classifier.fit(X_train, Y_train)
Y_predict = classifier.predict(X_test)

Accuracy = classifier.score(X_train, Y_train)
print(Accuracy)

Accuracy_test = classifier.score(X_test, Y_test)
print(Accuracy_test)